### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by orbiteleven** [acterglobal/code#2]
Every user in the system will be represented by a user profile.

- [ ] Users can create a new profile
- [ ] Users can update their profile information
- [ ] Users can add a picture to their profile
