### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by orbiteleven** [acterglobal/code#3]
A fixed set of taxonomically organized tags exist. These tags can be applied to both users and entities in the system.

- [ ] A fixed set of tags organized in to tag categories exist
- [ ] Users can select tags
- [ ] Entities can have tags assigned
