### ISSUE TITLE
Acters

### ISSUE THREAD

**Issue by orbiteleven** [acterglobal/code#4]
# Description
Acters are the building block onto which Groups, Organizations and Networks are built based on Acter Type. Actors can be linked to each other following a rule set based on the Acter Type:

## Groups
 - can be connected to 0 or 1 Organization
 - can join many Networks

## Organizations
 - can have 0 or more Groups
 - can join 0 or more Networks

## Networks
 - can be joined by Groups
 - can be joined by Organizations

# Tasks
- [ ] Acters can be created
- [ ] Acters can be joined by Users
- [ ] Acters can join other Acters according to the Acter Type rule set
